general:
  img_file_type: 'jpg'
  data_path: './data'
  result_path: './results'

training:
  batch_size: 4
  num_epochs: 10
  latent_dim: 256
  resolution: 256
  num_workers: 1
  num_channels: 3

  logging:
    interval: 1
    batch_size: 4

discriminator:
  optimizer:
    beta1: 0.999
    beta2: 0.5
    lr: 0.002

generator:
  ngf: 64
  z_dim: 256
  optimizer:
    beta1: 0.999
    beta2: 0.5
    lr: 0.002
